import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Sharpe Labs Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container px-6 py-6 mx-auto">
        <Navbar/>
        {children}</body>
    </html>
  );
}
